xmas = ['angel', 'artificial tree', 'bells', 'birth', 'blizzard', 'blustery', 'boots', 'bough', 'bow', 'candle',
        'candy', 'candy cane', 'card', 'carolers', 'caroling', 'carols', 'celebrate', 'celebration', 'ceremony',
        'charity', 'chestnuts', 'chill', 'chilly', 'chimney', 'Christmas', 'Christmas card', 'Christmas carol',
        'Christmas Eve', 'Christmas tree', 'Christmas tree stand', 'Christmas tide', 'cider', 'coal', 'cold', 'cookie',
        'creche', 'decorate', 'decorations', 'display', 'eggnog', 'elf', 'elves', 'eve', 'evergreen', 'exchange',
        'family', 'family reunion', 'Father Christmas', 'feast', 'Feliz Navidad', 'festival', 'festive', 'fir',
        'fireplace', 'firewood', 'frankincense', 'frosty', 'Frosty the Snowman', 'fruitcake', 'garland', 'gift',
        'gift giving', 'gingerbread', 'gingerbread house', 'gingerbread man', 'gingerbread woman', 'give', 'gold',
        'goodwill', 'goose', 'green', 'greetings', 'guest', 'happy', 'holiday', 'holly', 'hope', 'hot chocolate',
        'hot cider', 'hug', 'ice skates', 'icicle', 'icy', 'ivy', 'Jack Frost', 'Jesus', 'jingle bells', 'jolly', 'joy',
        'joyful', 'kings', 'Krampus', 'Kris Kringle', 'lights', 'list', 'log', 'love', 'manger', 'merry',
        'Merry Christmas', 'mince pie', 'mistletoe', 'mittens', 'myrrh', 'nativity', 'naughty', 'nice', 'nippy', 'Noel',
        'North Pole', 'nutcracker', 'occasion', 'ornaments', 'package', 'pageant', 'parade', 'partridge', 'party',
        'pie', 'pine tree', 'pine cone', 'plum pudding', 'poinsettia', 'popcorn string', 'presents', 'receive',
        'reindeer', 'rejoice', 'reunion', 'ribbon', 'Rudolph', 'Saint Nicholas', 'Santa Claus', 'scarf', 'Scrooge',
        'season', 'seasons greetings', 'shopping', 'skate', 'sled', 'sleigh', 'sleigh bells', 'snow', 'snowball',
        'snowfall', 'snow flake', 'snowman', 'snowy', 'socks', 'spirit', 'star', 'stocking', 'stocking stuffer',
        'sugarplum', 'sweater', 'tidings', 'tinsel', 'toboggan', 'togetherness', 'toy', 'tradition', 'tree', 'trimming',
        'trips', 'turkey', 'unwrap', 'vacation', 'visit', 'wassail', 'winter', 'wintertime', 'wintry', 'wise men',
        'wish', 'wonder', 'workshop', 'wrap', 'wrapping paper', 'wreath', 'yule log', 'yuletide']

hard = ['abruptly', 'absurd', 'abyss', 'affix', 'askew', 'avenue', 'awkward', 'axiom', 'azure', 'bagpipes', 'bandwagon',
        'banjo', 'bayou', 'beekeeper', 'bikini', 'blitz', 'blizzard', 'boggle', 'bookworm', 'boxcar', 'boxful',
        'buckaroo', 'buffalo', 'buffoon', 'buxom', 'buzzard', 'buzzing', 'buzzwords', 'caliph', 'cobweb', 'cockiness',
        'croquet', 'crypt', 'curacao', 'cycle', 'daiquiri', 'dirndl', 'disavow', 'dizzying', 'duplex', 'dwarves',
        'embezzle', 'equip', 'espionage', 'euouae', 'exodus', 'faking', 'fishhook', 'fixable', 'fjord', 'flapjack',
        'flopping', 'fluffiness', 'flyby', 'foxglove', 'frazzled', 'frizzled', 'fuchsia', 'funny', 'gabby', 'galaxy',
        'galvanize', 'gazebo', 'giaour', 'gizmo', 'glowworm', 'glyph', 'gnarly', 'gnostic', 'gossip', 'grogginess',
        'haiku', 'haphazard', 'hyphen', 'iatrogenic', 'icebox', 'injury', 'ivory', 'ivy', 'jackpot', 'jaundice',
        'jawbreaker', 'jaywalk', 'jazziest', 'jazzy', 'jelly', 'jigsaw', 'jinx', 'jiujitsu', 'jockey', 'jogging',
        'joking', 'jovial', 'joyful', 'juicy', 'jukebox', 'jumbo', 'kayak', 'kazoo', 'keyhole', 'khaki', 'kilobyte',
        'kiosk', 'kitsch', 'kiwifruit', 'klutz', 'knapsack', 'larynx', 'lengths', 'lucky', 'luxury', 'lymph', 'marquis',
        'matrix', 'megahertz', 'microwave', 'mnemonic', 'mystify', 'naphtha', 'nightclub', 'nowadays', 'numbskull',
        'nymph', 'onyx', 'ovary', 'oxidize', 'oxygen', 'pajama', 'peekaboo', 'phlegm', 'pixel', 'pizazz', 'pneumonia',
        'polka', 'pshaw', 'psyche', 'puppy', 'puzzling', 'quartz', 'queue', 'quips', 'quixotic', 'quiz', 'quizzes',
        'quorum', 'razzmatazz', 'rhubarb', 'rhythm', 'rickshaw', 'schnapps', 'scratch', 'shiv', 'snazzy', 'sphinx',
        'spritz', 'squawk', 'staff', 'strength', 'strengths', 'stretch', 'stronghold', 'stymied', 'subway', 'swivel',
        'syndrome', 'thriftless', 'thumbscrew', 'topaz', 'transcript', 'transgress', 'transplant', 'triphthong',
        'twelfth', 'twelfths', 'unknown', 'unworthy', 'unzip', 'uptown', 'vaporize', 'vixen', 'vodka', 'voodoo',
        'vortex', 'voyeurism', 'walkway', 'waltz', 'wave', 'wavy', 'waxy', 'wellspring', 'wheezy', 'whiskey',
        'whizzing', 'whomever', 'wimpy', 'witchcraft', 'wizard', 'woozy', 'wristwatch', 'wyvern', 'xylophone',
        'yachtsman', 'yippee', 'yoked', 'youthful', 'yummy', 'zephyr', 'zigzag', 'zigzagging', 'zilch', 'zipper',
        'zodiac']

animals = ['Aardvark', 'African elephant', 'Albatross', 'Alley cat', 'Alligator', 'Amphibian', 'Ant', 'Anteater',
           'Antelope', 'Ape', 'Armadillo', 'Asian elephant', 'Baboon', 'Badger', 'Bat', 'Bear', 'Beaver', 'Beetle',
           'Billy goat', 'Bison', 'Boar', 'Bobcat', 'Bovine', 'Bronco', 'Buck', 'Buffalo', 'Bug', 'Bull', 'Bunny',
           'Calf', 'Camel', 'Canary', 'Canine', 'Caribou', 'Cat', 'Caterpillar', 'Centipede', 'Chanticleer', 'Cheetah',
           'Chick', 'Chimpanzee', 'Chinchilla', 'Chipmunk', 'Clam', 'Cockatiel', 'Colt', 'Condor', 'Cougar', 'Cow',
           'Coyote', 'Crab', 'Crane', 'Creature', 'Crocodile', 'Crow', 'Cub', 'Cur', 'Cygnet', 'Deer', 'Dingo', 'Dodo',
           'Doe', 'Dog', 'Dolphin', 'Donkey', 'Dove', 'Drake', 'Duck', 'Eagle', 'Egret', 'Elephant', 'Elk', 'Emu',
           'Ewe', 'Falcon', 'Fawn', 'Feline', 'Ferret', 'Flamingo', 'Flee', 'Flies', 'Foal', 'Fowl', 'Fox', 'Frog',
           'Gander', 'Gazelle', 'Gelding', 'Gerbil', 'Gibbon', 'Giraffe', 'Goat', 'Goose', 'Gopher', 'Gorilla',
           'Grizzly bear', 'Guinea pig', 'Hamster', 'Hare', 'Hawk', 'Hedgehog', 'Heifer', 'Hippopotamus', 'Horse',
           'Hound', 'Hummingbird', 'Hyena', 'Ibis', 'Iguana', 'Jackal', 'Jackrabbit', 'Jaguar', 'Javalina', 'Jellyfish',
           'Jenny', 'Joey', 'Kangaroo', 'Kid', 'Kitten', 'Kiwi', 'Koala', 'Komodo dragon', 'Krill', 'Lamb', 'Lemming',
           'Lemur', 'Leopard', 'Lion', 'Lioness', 'Llama', 'Lobster', 'Lynx', 'Macaw', 'Manatee', 'Marmoset', 'Marmot',
           'Mink', 'Minnow', 'Mite', 'Mockingbird', 'Mole', 'Mongoose', 'Mongrel', 'Monkey', 'Moose', 'Mouse', 'Mule',
           'Mustang', 'Mutt', 'Nag', 'Narwhale', 'Newt', 'Ocelot', 'Octopus', 'Opossum', 'Orangutan', 'Orca', 'Osprey',
           'Ostrich', 'Otter', 'Owl', 'Ox', 'Pachyderm', 'Panda', 'Panther', 'Parakeet', 'Parrot', 'Peacock', 'Pelican',
           'Penguin', 'Pheasant', 'Pig', 'Pigeon', 'Piglet', 'Platypus', 'Pony', 'Pooch', 'Porcupine', 'Porpoise',
           'Primate', 'Puppy', 'Pussycat', 'Quail', 'Rabbit', 'Raccoon', 'Ram', 'Rat', 'Reptiles', 'Rhinoceros',
           'Robin', 'Rooster', 'Salamander', 'Sea lion', 'Seagull', 'Seal', 'Sheep', 'Sidewinder', 'Skunk', 'Sloth',
           'Snail', 'Snake', 'Songbird', 'Sow', 'Spider', 'Squid', 'Squirrel', 'Stallion', 'Steer', 'Stork', 'Stork',
           'Swan', 'Tadpole', 'Tapir', 'Terrapin', 'Thoroughbred', 'Tiger', 'Toad', 'Tortoise', 'Toucan', 'Turkey',
           'Uakari', 'Unicorn', 'Vixen', 'Vole', 'Vulture', 'Wallaby', 'Walrus', 'Warthog', 'Wasp', 'Weasel', 'Whale',
           'Wildebeast', 'Wolf', 'Wombat', 'Woodpecker', 'Worm', 'X-ray fish', 'Yak', 'Zebra']

finance = ['Balance', 'Balloon payment', 'Bank', 'Bankrupt', 'Barter', 'Bear', 'Beneficiary', 'Bid', 'Blue chip',
           'Bond', 'Bracket', 'Broker', 'Brokerage', 'Bull', 'Buying', 'Buyout', 'Calculation', 'Call', 'Capital gain',
           'Cartel', 'Cashier', 'Certificate', 'Certified', 'Chart', 'Churn', 'Circulation', 'Clearinghouse',
           'Collateral', 'Collect', 'Commission', 'Commodity', 'Common stock', 'Compensation', 'Competitor', 'Compound',
           'Conglomerate', 'Consolidation', 'Consortium', 'Consumer', 'Convertible', 'Correction', 'Cost', 'Counter',
           'Countersign', 'Credit', 'Currency', 'Custodian', 'Deal', 'Debenture', 'Debit', 'Debt', 'Deductible',
           'Deduction', 'Default', 'Delinquency', 'Demand', 'Depository', 'Depreciation', 'Depression', 'Deregulation',
           'Designation', 'Devaluation', 'Differential', 'Discount', 'Discretionary account', 'Distribution',
           'Diversify', 'Dividend', 'Dow Jones Average', 'Downturn', 'Draft', 'Driven', 'Dump', 'Earn', 'Economy',
           'Electronic', 'Elimination', 'Embezzlement', 'Endorse', 'Enterprise', 'Entity', 'Equity', 'Escrow',
           'ESOP (Employees Stock Ownership Plan)', 'Estimation', 'Evaluation', 'Exceed', 'Exchange rate', 'Exorbitant',
           'Expectation', 'Extortion', 'Failure', 'Falling price', 'Federal', 'Fees', 'Fiduciary', 'Finance', 'Fiscal',
           'Fixed', 'Float', 'Foreclosure', 'Forfeiture', 'Frugality', 'Fulfillment', 'Fund', 'Funds', 'Futures',
           'Gain', 'GDP', 'Gold', 'Government', 'Growth', 'Guarantee', 'Guaranty', 'High-interest', 'Hiring',
           'Identification', 'Illegal', 'Imprint', 'Income', 'Index', 'Industrial', 'Inflated price',
           'Insider information', 'Insolvent', 'Installment', 'Institution', 'Institutional trading', 'Insufficient',
           'Intangible', 'Interest', 'Interest-bearing', 'Intermediary', 'Intervention', 'Invalidate', 'Investment',
           'IRA', 'Issue', 'Joint account', 'Junk bond', 'Keogh plan', 'Kiting', 'Laundering', 'LBO (leveraged buyout)',
           'Lending rate', 'Leverage', 'Liability', 'Lien', 'Liquidity', 'Long-term', 'Low risk', 'Lucrative',
           'Maintain', 'Margin', 'Market', 'Maturity', 'Member', 'Mercantile', 'Merger', 'Money', 'Monopoly',
           'Municipals', 'Mutual funds', 'Negotiable', 'Non-speculative', 'Note', 'NYSE', 'Obligation', 'Odd lot',
           'Operation', 'Option', 'OTC (over the counter)', 'Overcompensate', 'Oversight', 'Ownership', 'Par value',
           'Payment', 'Peaks', 'Percent', 'Planning', 'Pledge', 'Points', 'Portfolio', 'Practice', 'Predetermine',
           'Preferred stock', 'Premium', 'Prepayment penalty', 'Principal', 'Product', 'Profit', 'Progressive',
           'Promissory note', 'Public', 'Quality', 'Qualm', 'Quantity', 'Questionable', 'Quick', 'Quittance', 'Quote',
           'Raid', 'Rally', 'Ramification', 'Rate', 'Ratio', 'Recession', 'Record', 'Recoup', 'Recourse', 'Redemption',
           'Reduction', 'Regulation', 'Reimburse', 'Reliability', 'Reserves', 'Retirement', 'Risk', 'Rumors', 'Sale',
           'Savings', 'Securities', 'Select', 'Sell-off', 'Selling', 'Shares', 'Short term', 'Shylock', 'Slump',
           'Solvency', 'Speculate', 'Speculative', 'Split', 'Stagflation', 'Stock split', 'Stocks', 'Subscription',
           'Summary', 'Supply and demand', 'Surety', 'Surplus', 'Survivorship', 'Swap', 'Takeover', 'Tax shelter',
           'Tax year', 'Tax-exempt bond', 'Taxes', 'Technical', 'Tender', 'Thrifts', 'Ticker tape', 'Trade',
           'Transaction', 'Transfer', 'Transferable', 'Treasury bill', 'Trends', 'Uncollected', 'Underwriter', 'Unit',
           'Unofficial', 'Unregulated', 'Unsecured', 'Untaxed', 'Usury', 'Utilities', 'Valuable', 'Value', 'Variable',
           'Vault', 'Venture', 'Void', 'Voucher', 'Wage', 'Warrant', 'Wide-ranging', 'Withdrawal', 'Yield',
           'Zero-coupon bond']

art = ['Ability', 'Absorbing', 'Abstract', 'Acclaimed', 'Acquisition', 'Acrylic', 'Adaptation', 'Adept', 'Aesthetic',
       'Aficionado', 'Analogous', 'Angular', 'Appreciation', 'Arrangement', 'Array', 'Artistic', 'Artlessness',
       'Assemblage', 'Assemble', 'Assist', 'Assistance', 'Asymmetry', 'Attempt', 'Attraction', 'Audience', 'Audience',
       'Authentic', 'Avid', 'Award-winning', 'Axis', 'Background', 'Balance', 'Baroque', 'Beauty', 'Beholder', 'Bias',
       'Blur', 'Bravado', 'Bravo', 'Brushwork', 'Caliber', 'Canvas', 'Captivate', 'Capture', 'Carve', 'Caution',
       'Celebrity', 'Ceramics', 'Chalk', 'Charcoal', 'Charisma', 'Clamor', 'Classic', 'Clay', 'Collaboration',
       'Collage', 'Collection', 'Color', 'Commanding', 'Commitment', 'Communication', 'Competition', 'Complementary',
       'Component', 'Composition', 'Concave', 'Concentration', 'Connoisseur', 'Contour', 'Contract', 'Contrast',
       'Contribution', 'Converge', 'Convex', 'Cool color', 'Coordination', 'Crafts', 'Creativity', 'Crescendo',
       'Crowd-pleasing', 'Culture', 'Curator', 'Curve', 'Dabble', 'Dazzle', 'Debut', 'Decor', 'Decorative',
       'Demonstration', 'Depth', 'Design', 'Device', 'Diagonal', 'Diffuse', 'Digital image', 'Direction',
       'Disorganized', 'Display', 'Distraction', 'Diverse', 'Diversity', 'Dramatic', 'Drive', 'Dynamic', 'Effect',
       'Element', 'Eloquence', 'Emotion', 'Endurance', 'Energy', 'Ensemble', 'Entertainment', 'Essence', 'Euphoric',
       'Evaluation', 'Exaggeration', 'Exalt', 'Execution', 'Exemplary', 'Exhibition', 'Exposure', 'Expression',
       'Expressive', 'Exquisite', 'Extraordinary', 'Facade', 'Facets', 'Facilitate', 'Falter', 'Fascination',
       'Features', 'Finalist', 'Flat', 'Flexible', 'Flourish', 'Fluid', 'Fluorescent', 'Focus', 'Foreground', 'Form',
       'Format', 'Forte', 'Framework', 'Frenzy', 'Fuzz', 'Gauge', 'Genius', 'Genre', 'Geometric', 'Gesture', 'Glare',
       'Glaze', 'Gloss', 'Graceful', 'Graphic', 'Harmony', 'Hatching', 'Hiatus', 'Highlight', 'Hone', 'Horizon line',
       'Hue', 'Humanities', 'Hype', 'Iconic', 'Idealization', 'Illumination', 'Illustration', 'Illustrious', 'Image',
       'Imagery', 'Imagination', 'Impact', 'Impression', 'Impressionist', 'Impressive', 'Impromptu', 'Inclination',
       'Inconsistent', 'Individual', 'Influence', 'Infusion', 'Innovative', 'Insight', 'Inspirational', 'Instrumental',
       'Integrity', 'Intensity', 'Intent', 'International', 'Interpretation', 'Inventive', 'Jagged', 'Jargon', 'Judge',
       'Judgment', 'Juxtaposition', 'Keen', 'Key', 'Landscape', 'Legendary', 'Light source', 'Lighting', 'Line',
       'Lively', 'Luminous', 'Luster', 'Lyrical', 'Magic', 'Major', 'Manifestation', 'Masterwork', 'Maximize', 'Meager',
       'Measure', 'Media', 'Medium', 'Memorable', 'Minimize', 'Minor', 'Mixed', 'Momentum', 'Mood', 'Motion',
       'Motivate', 'Motivation', 'Movement', 'Movies', 'Muse', 'Neutral', 'Niche', 'Nimble', 'Nostalgia', 'Notation',
       'Nuance', 'Ocher', 'Oomph', 'Opportunity', 'Opt', 'Optimal', 'Ornate', 'Outline', 'Outstanding', 'Oval',
       'Overlap', 'Overture', 'Painting', 'Palette', 'Parallel', 'Participation', 'Passionate', 'Pastel', 'Pattern',
       'Perception', 'Perpendicular', 'Persistence', 'Perspective', 'Perspiration', 'Phenomenal', 'Pigment', 'Pinnacle',
       'Placement', 'Popular', 'Portrait', 'Portrayal', 'Pose', 'Position', 'Potent', 'Pottery', 'Powerful', 'Practice',
       'Prelude', 'Premiere', 'Presence', 'Pressure', 'Primary', 'Professional', 'Profile', 'Project', 'Promising',
       'Proportion', 'Provocative', 'Quality', 'Quantity', 'Quick', 'Quintessential', 'Quirk', 'Realistic', 'Recede',
       'Recognition', 'Refine', 'Repetition', 'Reputation', 'Resilient', 'Resonance', 'Response', 'Restraint',
       'Retrospective', 'Revival', 'Rhythm', 'Scale', 'Scenery', 'Scheme', 'Sculpt', 'Sculpture', 'Secondary', 'Shade',
       'Shadow', 'Shallowness', 'Shapes', 'Sharp', 'Sketch', 'Skill', 'Solo', 'Soulful', 'Space', 'Spectacular',
       'Spectrum', 'Speculation', 'Spin', 'Spirit', 'Spontaneity', 'Spotlight', 'Stamina', 'Star', 'Status',
       'Still life', 'Stipple', 'Straight', 'Streak', 'Strength', 'Stretch', 'Stunning', 'Style', 'Sublime', 'Subtle',
       'Symbolic', 'Symmetry', 'Talent', 'Technical', 'Technicolor', 'Technique', 'Tertiary', 'Texture', 'Tint', 'Tone',
       'Training', 'Transform', 'Transformation', 'Transmission', 'Ultimate', 'Unbelievable', 'Unconventional',
       'Unique', 'Unity', 'Unprecedented', 'Unusual', 'Value', 'Vanguard', 'Vanishing point', 'Variation', 'Variety',
       'Veer', 'Version', 'Vertical', 'Vibrant', 'Viewpoint', 'Visibility', 'Vision', 'Visual', 'Vital', 'Volatile',
       'Warm', 'Watercolor', 'Whirl', 'Zeal', 'Zest', 'Zip']


gallows = {
    7: "".join(['\t______\n', '\t|     \n', '\t|\n', '\t|\n', '\t|\n', '\t|\n', '____________\n']),
    6: "".join(['\t______\n', '\t|    |\n', '\t|\n', '\t|\n', '\t|\n', '\t|\n', '____________\n']),
    5: "".join(['\t______\n', '\t|    |\n', '\t|    @\n', '\t|\n', '\t|\n', '\t|\n', '____________\n']),
    4: "".join(['\t______\n', '\t|    |\n', '\t|    @\n', '\t|    |\n', '\t|\n', '\t|\n', '____________\n']),
    3: "".join(['\t______\n', '\t|    |\n', '\t|    @\n', '\t|   /|\n', '\t|\n', '\t|\n', '____________\n']),
    2: "".join(['\t______\n', '\t|    |\n', '\t|    @\n', '\t|   /|\\\n', '\t|\n', '\t|\n', '____________\n']),
    1: "".join(['\t______\n', '\t|    |\n', '\t|    @\n', '\t|   /|\\\n', '\t|   /\n', '\t|\n', '____________\n']),
    0: "".join(['\t______\n', '\t|    |\n', '\t|    @\n', '\t|   /|\\\n', '\t|   / \\\n', '\t|\n', '____________\n'])
    }
